build: false

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
  matrix:
    - PYTHON_VERSION: 3.9
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - CALL "%MINICONDA%\\Scripts\\activate.bat"
  # Remove cygwin because it clashes with conda
  # see http://help.appveyor.com/discussions/problems/3712-git-remote-https-seems-to-be-broken
  - rmdir C:\\cygwin /s /q
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n abel-env python=%PYTHON_VERSION% numpy scipy cython"
  - activate abel-env
  - conda install coverage pytest pytest-cov pip
  # win32 conda has only oudated Setuptools, so install them from PyPI
  - python -m pip install --upgrade setuptools packaging
  - dir 
  - pip install . -v --no-build-isolation

test_script:
  - cd "%TMP%"
  - pytest -v --cov=pyabel --pyargs pyabel
