build: false

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda-x64
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.7
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.7
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  # Remove cygwin because it clashes with conda
  # see http://help.appveyor.com/discussions/problems/3712-git-remote-https-seems-to-be-broken
  - rmdir C:\\cygwin /s /q
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n abel-env python=%PYTHON_VERSION% numpy scipy cython"
  - activate abel-env
  - pip install coverage pytest pytest-cov
  - dir 
  - "cd C:\\projects\\PyAbel"
  - pip install .



test_script:
  - "cd C:\\"
  - pytest --cov=abel --pyargs abel
